

export const ASSETS = {
    Fav: '/icons/favicon.ico',
    Image: '/images/logo.png',
    WestWardLogoRed: '/images/logo.svg',
    ArrowLeft:'/images/left-red-arrow.png',
    WestWard:'images/Westward_Full_Reverse.svg',
    WhiteArrow:'images/whiteArrow.png',
    VideoHeader:'/videos/videoMobile.mp4',
    DownArrow: 'images/downArrow.png',
    Couple:'/images/couple.png',
    Bench:'/images/bench.png',
    CircleText:'/images/circleText.png',
    Flats:'/images/flats.png',
    Map:'/images/map.png',
    Flowers:'/images/flowers.png',
    Walk:'/images/walk.png',
    Ramen:'/images/ramen.png',
    ClothShop:'/images/clothShop.png',
    Bakery:'/images/bakery.png',
    Cycle:'/images/cycle.png',
    Bus:'/images/bus.png',
    BlueSofa:'/images/blueSofa.png',
    Kitchen:'/images/kitchen.png',
    LivingRoom:'/images/livingRoom.png',
    RedArrows:'/images/redArrows.png',
    TVlounge:'/images/TVlounge.png',
    ChairIcon:'/icons/chair.png',
    CycleIcon:'/icons/cycle.png',
    DogIcon:'/icons/dog.png',
    DownArrowIcon:'/icons/downArrow.png',
    FireIcon:'/icons/fireIcon.png',
    OppositeArrows:'/icons/oppositeArrows.png',
    UpArrowsIcon:'/icons/upArrows.png',
    WorkingIcon:'/icons/workingMan.png',
    
}